services:
  - type: web
    name: webbingo
    env: node
    plan: free
    buildCommand: npm run install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 